### ISSUE TITLE
read_data error: MSACAT

### ISSUE THREAD

**Issue by CynthiaBland** [Westat-Transportation/summarizeNHTS#1]
When reading in the 2009 data, I get an error (attached) about the MSACAT object not found. I searched the .csv files and found that field on the non-weights files. It looks like this error is coming from the "derived_variable_config.csv" file Cell D2. Do you have suggestions?

[MSACAT_error.txt](https://github.com/Westat-Transportation/summarizeNHTS/files/1633065/MSACAT_error.txt)

**Comment by AnthonyFucci** [comment]
I think you are using the github readme page demo as a template and getting this issue because that example call does name all of its parameters (it should, I have updated it). The vignette and extended demo were up-to-date, and there is also an example in the documentation for read_data().

I think you can resolve this issue by relying on the directory parameter defaults like in the first example below or by specifying your own directory like in the second example below.

```
download_nhts_data("2009")
dataset <- read_data("2009")
```

```
download_nhts_data("2009", exdir="C:/NHTS")
dataset <- read_data("2009", csv_path="C:/NHTS")
```

If you use the first example, you should work with RStudio project files (.RProj) so that your directory is already set. Thanks for pointing this out!

**Comment by afcates** [comment]
Looks like this was resolved. I am going to close this issue. Thank you for bringing it to our attention Cynthia.
