### ISSUE TITLE
3 Weird Characters and 

### ISSUE THREAD

**Issue by murraywisdot** [Westat-Transportation/summarizeNHTS#6]
This happens before I run the following step in prepping the data
> nhts_data <- read_data (‘2017’)
For example in the household.csv, column A should read HOUSEID, not Ï»¿HOUSEID. The household, person, and trip csv files all had the 3 weird characters in the first column name HOUSEID. The other files (household_weights.csv, location.csv, person_weights.csv, and vehicle.csv) did not have these weird characters.

Later when looking at the person and trip files, I have noticed that the number of observations and weighted statistic are not OK.

**Comment by AnthonyFucci** [comment]
The weird "Ï»¿" characters suggests that the file was modified in a windows program that prepended the file with what's called a Byte Order Mark (BOM) when saved. The easiest instructions I see out there for removing the hidden unwanted character from a csv file is to open the file in notepad++, change the encoding, and then save (https://www.larshaendler.com/2015/01/20/remove-bom-with-notepad/). You could also try going back to your original household.csv file and try understanding the software or steps that modified the file in this way, to see if there are ways you can avoid it.

Thanks for filing this. I'm going to label it a bug because maybe there is something we can do in our read data functions to make them care about not caring about these byte order marks.

**Comment by AnthonyFucci** [comment]
updated prepare_add_on_files() to remove byte order marks when they exist
